name: Myanmar Tools CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

jobs:

  # Training Data Project
  training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: '8'
      - name: Training Data
        run: |
          cd training
          mvn compile
          mvn test

  # Generate-Converter Project
  gen-conv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: '8'
      - name: Generate-Converter
        run: |
          cd genconvert
          mvn compile
          mvn test

  # Check consistency between genconvert and compiled converters
  genconvert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: '8'
      - name: Consistency genconvert vs compiled
        run: |
          make transcompile
          # There should not be any dirty files:
          git update-index --refresh
          git diff-index HEAD --exit-code

  # CPP Client
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cpp-check
        run: |
          sudo apt-get -y install cmake
          cd clients/cpp
          CXXFLAGS="-w" cmake CMakeLists.txt
          make
          make test

  # Java Client
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          java-version: '7'
      - name: Java client test
        run: |
          cd clients/java
          mvn compile
          mvn test
      
  # PHP Client (minimum PHP version)
  php-min-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with min version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
      - uses: "ramsey/composer-install@v1"
      - run: ./vendor/bin/phpunit --configuration clients/php/phpunit.xml

  # PHP Client (latest PHP version)
  php-latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with the latest version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
      - uses: "ramsey/composer-install@v1"
      - run: ./vendor/bin/phpunit --configuration clients/php/phpunit.xml

  # Python Client
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python  
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Python client test
        run: |
          cd clients/python
          python setup.py install
          python -m unittest

  # Swift Client on macOS
  swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.5'
      - run: make client-swift-test
